# Generated by Django 6.0 on 2026-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=4005),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twofactorotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
