# Generated by Django 6.0 on 2026-03-11 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f99e465-a6c2-4a06-8f3e-d3fff8a4684d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
