# Generated by Django 6.0 on 2026-03-05 04:44

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^CB[0-9]{2}[A-Z]{3}-DEPT$', message='Department code formati CB24AIM-DEPT kabi bolishi kerak!')])),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
